[package]
name = "starknet-rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["with_mimalloc"]
with_mimalloc = ["mimalloc"]

[workspace]
members = ["crates/starknet-contract-class", "fuzzer", "cli"]

[workspace.dependencies]
cairo-vm = { version = "0.5.2", features = ["cairo-1-hints"]}

[dependencies]
cairo-lang-starknet = "1.1.0"
cairo-lang-casm = "1.1.0"
cairo-vm = { workspace=true, features = ["cairo-1-hints"]}
getset = "0.1.2"
lazy_static = "1.4.0"
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1.45"
num-traits = "0.2.15"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sha3 = "0.10.1"
starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev="a891109ecc9c269e91b1afd2d44bc597728e1172", features = [
    "testing",
] }
starknet-crypto = "0.4.3"
thiserror = "1.0.32"
awc = "3.1.1"
mimalloc = { version = "0.1.29", default-features = false, optional = true }
hex = "0.4.3"
cargo-llvm-cov = "0.5.14"

starknet-contract-class = { path = "crates/starknet-contract-class" }
once_cell = "1.17.1"

[dev-dependencies]
assert_matches = "1.5.0"
coverage-helper = "0.1.0"

[[bench]]
path = "bench/internals.rs"
name = "internals"
harness = false

[profile.release.package.fuzzer]
strip = "debuginfo"
overflow-checks = true
opt-level = 3
debug = true
debug-assertions = true
