[package]
name = "starknet_in_rust"
version = "0.3.0"
edition = "2021"
description = "A Rust implementation of Starknet execution logic"
license = "Apache-2.0"

[features]
default = ["with_mimalloc"]
with_mimalloc = ["mimalloc"]
cairo_1_tests = []

[workspace]
members = ["cli", "fuzzer"]

[workspace.dependencies]
cairo-vm = { version = "0.8.1", features = ["cairo-1-hints"] }
starknet_api = "0.1.0"
num-traits = "0.2.15"

[dependencies]
cairo-lang-starknet = "2.0.2"
cairo-lang-casm = "2.0.2"
cairo-vm = { workspace = true, features = ["cairo-1-hints"] }
getset = "0.1.2"
lazy_static = "1.4.0"
num-bigint = { version = "0.4", features = ["serde"] }
num-integer = "0.1.45"
num-traits = { workspace = true }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = [
    "arbitrary_precision",
    "raw_value",
] }
sha3 = "0.10.1"
starknet_api = { workspace = true }
starknet-crypto = "0.5.1"
thiserror = "1.0.32"
mimalloc = { version = "0.1.29", default-features = false, optional = true }
hex = "0.4.3"
anyhow = "1.0.66"
once_cell = "1.17.1"

[dev-dependencies]
assert_matches = "1.5.0"
coverage-helper = "0.1.0"

[[bench]]
path = "bench/internals.rs"
name = "internals"
harness = false
